export const teamsSampleData = [
  {
    teamId: "6f17d236-a9f0-450c-96bf-b057c5bd0217",
    teamName: "India",
    players: [
      {
        id: "p1",
        name: "R Sharma",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p2",
        name: "V Kolhi",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p3",
        name: "J Bumrah",
        type: "bowler",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
    ],
    matches: 0,
    wins: 0,
    loss: 0,
    points: 0,
  },
  {
    teamId: "91dc6008-61a9-4770-b81d-81bfd6bef4f0",
    teamName: "Pakistan",
    players: [
      {
        id: "p1",
        name: "B Azam",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p2",
        name: "M Rizwan",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p3",
        name: "M Amir",
        type: "bowler",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
    ],
    matches: 0,
    wins: 0,
    loss: 0,
    points: 0,
  },
  {
    teamId: "2e8113ed-9cec-45e0-a071-999a333cc7e6",
    teamName: "England",
    players: [
      {
        id: "p1",
        name: "J Root",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p2",
        name: "J Butler",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p3",
        name: "J Archer",
        type: "bowler",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
    ],
    matches: 0,
    wins: 0,
    loss: 0,
    points: 0,
  },
  {
    teamId: "4d7b8e62-bc0b-4ce9-88dc-c7582dfa8941",
    teamName: "New Zealand",
    players: [
      {
        id: "p1",
        name: "D Convey",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p2",
        name: "K Wilimson",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p3",
        name: "M Santner",
        type: "bowler",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
    ],
    matches: 0,
    wins: 0,
    loss: 0,
    points: 0,
  },
  {
    teamId: "ad92bb22-fd63-49b7-bd85-687b7873530d",
    teamName: "Australia",
    players: [
      {
        id: "p1",
        name: "T Head",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p2",
        name: "S Smith",
        type: "batsman",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
      {
        id: "p3",
        name: "M Starc",
        type: "bowler",
        runs: 0,
        balls: 0,
        wickets: 0,
        matches: 0,
      },
    ],
    matches: 0,
    wins: 0,
    loss: 0,
    points: 0,
  },
];
